name: Cleanup Workflows

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'Workflow file name to clean up (e.g., update-words.yml)'
        required: true
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup GitHub CLI
        run: |
          # GitHub CLI is pre-installed on GitHub-hosted runners
          gh --version
      
      - name: Run cleanup script
        run: |
          ./.github/scripts/cleanup-workflows.sh ${{ github.event.inputs.workflow_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 