name: Scrape and Deploy

on:
  schedule:
    # Run every day at 3:00 AM Eastern Time (7:00 UTC)
    - cron: '0 7 * * *'
  
  # Allow manual triggers for testing
  workflow_dispatch:
  
  # Also run on pushes to the main branch
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run scraper
        run: |
          echo "Starting to scrape Wordle answers from Rock Paper Shotgun..."
          python scraper.py
          echo "Scraping completed successfully"
      
      - name: List updated files
        run: |
          echo "Current word count: $(cat words.json | jq '. | length')"
          echo "Last updated: $(cat metadata.json | jq -r '.last_updated')"
          
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment 